Mint Signup Page Clone
mohapakram/mint-signup-page-clone pull request #1
Opened 2020-06-03 09:49 UTC by OlawaleJoseph

# This pull request features a cloned signup page of [MInt](http://accounts.intuit.com/signup.html).
 
## This branch features the following

- Creating a form
- Using different input types
- Using form attributes such as method, action.
- Writing modularized CSS code
- Using of Linters and Sticklers

2020-06-03 12:28 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @OlawaleJoseph and @mohapakram   :handshake: 

### Good job so far :clap:  your project is looking good :medal_sports: 

### there are still some changes to get the project approved :point_down:
- You have stickler files in your repository but I don't see any stickler checks in the pull request, please go to https://stickler-ci.com/ and enable stickler.
- In your Readme file there is non link to the live demo, please use http://raw.githack.com/ and update your readme file.
- The project should have a sign-in button:
##### Sign In Button
- [ ] It has a Sign In button at the top right corner ([link to page](https://accounts.intuit.com/signup.html))

Original:
![Screenshot from 2020-06-03 13-12-40](https://user-images.githubusercontent.com/26064042/83635394-0ffde480-a59c-11ea-84d3-0da99619f056.png)
Your project:
![Screenshot from 2020-06-03 13-13-53](https://user-images.githubusercontent.com/26064042/83635432-1e4c0080-a59c-11ea-89c9-0a086672cb1f.png)
- The page should have the intuit logo and products:
##### Intuit logo
- [ ] It shows the Intuit logo above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] The intuit logo is an embedded image that is horizontally centered ([link to page](https://accounts.intuit.com/signup.html))

##### Intuit products
- [ ] The products row is under the Intuit logo and above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

Original:
![Screenshot from 2020-06-03 13-15-02](https://user-images.githubusercontent.com/26064042/83635586-64a15f80-a59c-11ea-8da6-249eb38df5aa.png)
Your Project:
![Screenshot from 2020-06-03 13-16-30](https://user-images.githubusercontent.com/26064042/83635621-75ea6c00-a59c-11ea-90ae-f828d65b4d81.png)
- The bottom of the form is different from the original:
###### Bottom
- [ ] It has a disclaimer text that matches the context and style of the original page ([link to page](https://accounts.intuit.com/signup.html))
Original
![Screenshot from 2020-06-03 13-20-07](https://user-images.githubusercontent.com/26064042/83635996-180a5400-a59d-11ea-987d-b1d62a1a44cd.png)
Your Project:
![Screenshot from 2020-06-03 13-20-17](https://user-images.githubusercontent.com/26064042/83636008-20fb2580-a59d-11ea-9461-53bb4fd4e99b.png)
- Having a footer is required:
##### Footer
- [ ] It contains copyright and address information ([link to page](https://accounts.intuit.com/signup.html))
Your project:
![Screenshot from 2020-06-03 13-22-05](https://user-images.githubusercontent.com/26064042/83636131-57d13b80-a59d-11ea-934f-49d25fa228ab.png)
Original:
![Screenshot from 2020-06-03 13-21-57](https://user-images.githubusercontent.com/26064042/83636144-5d2e8600-a59d-11ea-9bf3-64219eec7931.png)
### Check the comments for more details.
### Please implement the required changes and ask for another code review.

2020-06-04 01:05 UTC, voscarmv commented
# Pull Request under the review by Oscar Mier (TSE) 👨‍💻

2020-06-04 01:21 UTC, voscarmv requested changes
# Great work implementing the requested changes team! 🔨 👨‍💻 🔧 
## However, additional changes are required... ⚙️ ⚙️ 

Please use this HTML validator before submitting any code review:

https://validator.w3.org/nu/

When running this validator, the following error was found:

- Please fix this by removing the unnecesary `type` attribute from your `<script>` tag.
![image](https://user-images.githubusercontent.com/2739245/83703799-1446f380-a5d6-11ea-9b59-734f21125182.png)

**[OPTIONAL]** Use semantic `<nav>`, `<main>` and `<footer>` tags to section your `index.html` page! This will make your page easier to process by [web spiders](https://en.wikipedia.org/wiki/Web_crawler) 🕸️ 🕷️  and it will help robots improve your `SEO` 🤖!

### Before re-submitting, please also check the comments I've left on your code for additional changes! 🗨️ 🧑‍💻 

# Happy coding! 😄 👍

2020-06-04 01:21 UTC, voscarmv commented on style.css
> +/* Form */
Please remove **all** comments from your CSS. This will make your code look cleaner ✨

2020-06-04 07:44 UTC, mohapakram commented
@voscarmv Hi, thank you for the feedback.
we don't have any scripts in our HTML but the service we use to serve the live demo may add some scripts and we have no control over it so please when checking our HTML for validation use our original HTML file (index.html) in the repo and not the live demo link.

2020-06-04 07:51 UTC, mohapakram commented on style.css
> +/* Form */
In the project description, there is a link to an article talking about CSS best practices and they mentioned using a CSS Table of Contents as a best practice. 

check it right here: https://speckyboy.com/good-bad-css-practices/

Thank you for the review.

2020-06-04 20:06 UTC, tirthajyoti-ghosh commented
# Pull Request under review by T. Ghosh (TSE)

2020-06-04 20:22 UTC, tirthajyoti-ghosh approved these changes
# Status: Approved✔

Great job on applying the changes. It's 👍 from me.
However, consider making these optional changes.

Check the comments.

2020-06-04 20:28 UTC, tirthajyoti-ghosh commented on index.html
> +            <input type="text" name="email" id="email" required />
[OPTIONAL] Make your input `type` be `email`. Eg., `<input type="email"...` for email inputs.

2020-06-04 20:30 UTC, tirthajyoti-ghosh commented on index.html
> +            <input type="number" name="phone" id="phone" required />
[OPTIONAL] Make your input `type` be `tel`. Eg., <input type="tel"... for phone number inputs.

2020-06-04 20:34 UTC, tirthajyoti-ghosh reviewed
Consider applying these small and optional changes before merging.

Good luck on your next projects ✨

2020-06-05 06:32 UTC, OlawaleJoseph commented on index.html
> +            <input type="text" name="email" id="email" required />
Resolved

2020-06-05 06:33 UTC, OlawaleJoseph commented on index.html
> +            <input type="number" name="phone" id="phone" required />
Resolved. Thanks for the feedback

2020-06-05 07:44 UTC, merged